/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.edu.ifsp.aluno;

import java.io.IOException;

import br.edu.ifsp.aluno.api.CharactersApi;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    // public static void main(String[] args) throws IOException, InterruptedException {
    //     CharactersApi characterApi = new CharactersApi(
    //         "https://gateway.marvel.com:443/v1/public/characters", 
    //         "f6415d04b3defd3908c07d2c02c88516", 
    //         "f4c2c921f82fa5a4f2ccdc7a2a13819d"
    //     );

    //     System.out.println(characterApi.searchByIdCharacter(1009610));
    // }
}
